language: go

env:
  - REDIS_HOST=localhost
  - GO_REPO_FULLNAME="github.com/firmeve/firmeve"

services:
  - redis-server

go:
  - 1.12.x

git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

before_install:
  - GO_REPO_NAMESPACE=${GO_REPO_FULLNAME%/*}
  # relies on GOPATH to contain only one directory...
  - mkdir -p ${GOPATH}/src/${GO_REPO_NAMESPACE}
  - ln -sv ${TRAVIS_BUILD_DIR} ${GOPATH}/src/${GO_REPO_FULLNAME}
  - cd ${GOPATH}/src/${GO_REPO_FULLNAME}
install:
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls
  - go get github.com/smartystreets/goconvey


#before_script:
#  - cd project
#  - echo `pwd`

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v -race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)