language: go

env:
  global:
    - REDIS_HOST=localhost
    - FIRMEVE_BASE_PATH=../testdata

services:
  - redis-server

go:
  - 1.12.x

git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

before_install:
  - go get github.com/mattn/goveralls
#  - go get github.com/go-playground/overalls
#  - go get github.com/smartystreets/goconvey

#before_script:
#  - cd project
#  - echo `pwd`

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go vet -atomic -asmdecl ./...
  - go test -v -race -count=1 ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)